default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: morango_web
  username: admin
  password: 44262718
  host: localhost
  port: 5432


production:
  <<: *default
  database: morango_web_production
  username: admin
  password: 44262718
  host: localhost
  port: 5432
